version: '3.4'

services:

  #redis:
  #  image: redis:alpine

  backend-api:
    image: ${DOCKER_REGISTRY-nigel}/nigeldaprbackendapi:${TAG:-latest}
    build:
      context: .
      dockerfile: Nigel.Dapr.BackendApi/Dockerfile

  backend-api-dapr:
    image: "daprio/daprd:1.9.0"
    network_mode: "service:backend-api"
    depends_on:
      - backend-api

  front-api:
    image: ${DOCKER_REGISTRY-nigel}/nigeldaprfrontapi:${TAG:-latest}
    build:
      context: .
      dockerfile: Nigel.Dapr.FrontApi/Dockerfile

  front-api-dapr:
    image: "daprio/daprd:1.9.0"
    network_mode: "service:front-api"
    depends_on:
      - front-api
