apiVersion: apps/v1
kind: Deployment
metadata:
  name: daprbackend
  labels:
    app: daprbackend
spec:
  selector:
    matchLabels:
      app: daprbackend
  replicas: 1
  template:
    metadata:
      name: daprbackend
      labels:
        app: daprbackend
    spec:
      containers:
        - name: daprbackend
          image: secondgalaxy/nigeldaprbackendapi:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
          # Define the ASP.NET Core ports
          - containerPort: 5000
          - containerPort: 443
          env:
          # The Azure Storage connection string for clustering is injected as an environment variable
          # It must be created separately using a command such as:
          # > kubectl create secret generic az-storage-acct --from-file=key=./az-storage-acct.txt
          #- name: STORAGE_CONNECTION_STRING
          #  valueFrom:
          #    secretKeyRef:
          #      name: az-storage-acct
          #      key: key
          # Configure settings to let Orleans know which cluster it belongs to and which pod it is running in
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
            value: "120"
          - name: REDIS
            value: "redis" # The name of the redis service 
      terminationGracePeriodSeconds: 180
      imagePullSecrets:
        - name: registry-jees
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

---
# In order to be able to access the service from outside the cluster, we will need to add a Service object
apiVersion: v1
kind: Service
metadata:
  name: daprbackend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    name: http
  selector:
    app: daprbackend

# For RBAC-enabled clusters, the Kubernetes service account for the pods may also need to be granted the required access:
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
- apiGroups: [ "" ]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ''
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: ''
