apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: demodapr-statestore
  namespace: demo
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379  # value: 192.168.3.10:6379
  - name: actorStateStore
    value: "true"